# Generated by Django 2.0.3 on 2018-08-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fence_nums',
            new_name='fans_nums',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='分类等级', max_length=10, verbose_name='分类等级'),
        ),
    ]
