# Generated by Django 2.0.3 on 2018-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0002_auto_20180810_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='person',
            name='play_nums',
            field=models.IntegerField(default=0, help_text='播放数', verbose_name='播放数'),
        ),
    ]
