# Generated by Django 2.0.3 on 2018-08-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0003_auto_20180810_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoorarticle',
            name='is_video_or_article',
            field=models.CharField(help_text='视频或文章', max_length=4, null=True, verbose_name='视频或文章'),
        ),
    ]
