# Generated by Django 2.0.3 on 2018-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0005_videoorarticle_cover_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='up主', max_length=30, verbose_name='up主')),
                ('title', models.CharField(help_text='标题', max_length=30, verbose_name='标题')),
                ('desc', models.TextField(help_text='描述', verbose_name='描述')),
                ('url', models.CharField(help_text='链接', max_length=255, verbose_name='链接地址')),
                ('cover_img_url', models.CharField(help_text='封面图', max_length=255, null=True, verbose_name='封面图')),
                ('view_nums', models.IntegerField(default=0, help_text='阅读数', verbose_name='阅读数')),
                ('comments', models.IntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('coins', models.IntegerField(default=0, help_text='硬币数', verbose_name='硬币数')),
                ('collections', models.IntegerField(default=0, help_text='收藏数', verbose_name='收藏数')),
                ('likes', models.IntegerField(default=0, help_text='喜欢数', verbose_name='喜欢数')),
                ('shares', models.IntegerField(default=0, help_text='分享数', verbose_name='分享数')),
                ('publish_time', models.DateTimeField(help_text='发布日期', verbose_name='发布日期')),
                ('tags', models.CharField(help_text='标签集', max_length=200, verbose_name='标签集')),
                ('category', models.CharField(help_text='分类集', max_length=50, verbose_name='分类集')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='up主', max_length=30, verbose_name='up主')),
                ('title', models.CharField(help_text='标题', max_length=30, verbose_name='标题')),
                ('desc', models.TextField(help_text='描述', verbose_name='描述')),
                ('url', models.CharField(help_text='链接', max_length=255, verbose_name='链接地址')),
                ('play_nums', models.IntegerField(default=0, help_text='播放数', verbose_name='播放数')),
                ('danmu_nums', models.IntegerField(default=0, help_text='弹幕数', verbose_name='弹幕数')),
                ('comments', models.IntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('coins', models.IntegerField(default=0, help_text='硬币数', verbose_name='硬币数')),
                ('collections', models.IntegerField(default=0, help_text='收藏数', verbose_name='收藏数')),
                ('likes', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('shares', models.IntegerField(default=0, help_text='分享数', verbose_name='分享数')),
                ('publish_time', models.DateTimeField(help_text='发布日期', verbose_name='发布日期')),
                ('tags', models.CharField(help_text='标签集', max_length=200, verbose_name='标签集')),
                ('category', models.CharField(help_text='分类集', max_length=50, verbose_name='分类集')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.DeleteModel(
            name='VideoOrArticle',
        ),
    ]
