# Generated by Django 2.0.3 on 2018-08-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0006_auto_20180811_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='view_nums',
            new_name='views',
        ),
    ]
