# Generated by Django 2.0.3 on 2018-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0007_auto_20180811_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_box',
            field=models.CharField(help_text='图源箱', max_length=500, null=True, verbose_name='图源箱'),
        ),
    ]
