# Generated by Django 2.0.3 on 2018-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0009_auto_20180813_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cid',
            field=models.IntegerField(help_text='cv号', null=True, unique=True, verbose_name='cv号'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sid',
            field=models.IntegerField(help_text='av号或cv号', null=True, unique=True, verbose_name='av号或cv号'),
        ),
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.IntegerField(help_text='av号', null=True, unique=True, verbose_name='av号'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='分类名', max_length=30, unique=True, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.IntegerField(help_text='用户uid', unique=True, verbose_name='用户uid'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='标签名', max_length=30, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(help_text='链接', max_length=255, verbose_name='链接地址'),
        ),
    ]
