# Generated by Django 2.0.3 on 2018-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0010_auto_20180813_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sid',
            field=models.CharField(help_text='av号或cv号', max_length=30, null=True, unique=True, verbose_name='av号或cv号'),
        ),
    ]
