# Generated by Django 2.0.3 on 2018-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0011_auto_20180813_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='cid',
            field=models.IntegerField(default=1, help_text='cv号', primary_key=True, serialize=False, verbose_name='cv号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.IntegerField(help_text='用户uid', primary_key=True, serialize=False, verbose_name='用户uid'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.IntegerField(default=1, help_text='av号', primary_key=True, serialize=False, verbose_name='av号'),
        ),
    ]
