# Generated by Django 2.0.3 on 2018-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0012_auto_20180813_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cid',
            field=models.IntegerField(help_text='cv号', primary_key=True, serialize=False, verbose_name='cv号'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.IntegerField(help_text='av号', primary_key=True, serialize=False, verbose_name='av号'),
        ),
    ]
