# Generated by Django 2.0.3 on 2018-08-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0013_auto_20180813_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(help_text='分类code', max_length=20, null=True, verbose_name='分类code'),
        ),
    ]
