# Generated by Django 2.0.3 on 2018-08-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0014_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='标题', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='标题', max_length=50, verbose_name='标题'),
        ),
    ]
