# Generated by Django 2.0.3 on 2018-08-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0015_auto_20180813_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_box',
            field=models.TextField(help_text='图源箱', null=True, verbose_name='图源箱'),
        ),
    ]
