# Generated by Django 2.0.3 on 2018-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0016_auto_20180813_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plat_from',
            field=models.CharField(default='PC端', help_text='平台', max_length=30, verbose_name='平台'),
        ),
    ]
