# Generated by Django 2.0.3 on 2018-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0017_auto_20180814_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_person',
            field=models.CharField(help_text='被回复用户', max_length=30, null=True, verbose_name='被回复用户'),
        ),
    ]
