# Generated by Django 2.0.3 on 2018-08-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0018_auto_20180814_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.CharField(help_text='评论用户', max_length=30, unique=True, verbose_name='评论用户'),
        ),
    ]
