# Generated by Django 2.0.3 on 2018-08-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0020_auto_20180814_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('sid', 'person', 'floor', 'publish_time')},
        ),
    ]
