# Generated by Django 2.0.3 on 2018-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0021_auto_20180814_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[(0, '视频'), (1, '文章')], default=0, help_text='种类', max_length=4, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sid',
            field=models.CharField(help_text='id号', max_length=30, null=True, verbose_name='id号'),
        ),
    ]
