# Generated by Django 2.0.3 on 2018-08-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0022_auto_20180815_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='play_game_list',
        ),
    ]
