# Generated by Django 2.0.3 on 2018-08-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0023_remove_person_play_game_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(default=1, help_text='标签id', primary_key=True, serialize=False, verbose_name='标签id'),
            preserve_default=False,
        ),
    ]
