# Generated by Django 2.0.3 on 2018-08-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0024_auto_20180815_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.CharField(help_text='描述', max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='tag',
            name='cover_url',
            field=models.CharField(help_text='标签图标', max_length=255, null=True, verbose_name='标签图标'),
        ),
        migrations.AddField(
            model_name='tag',
            name='publish_time',
            field=models.DateTimeField(help_text='发布时间', null=True, verbose_name='发布时间'),
        ),
    ]
