# Generated by Django 2.0.3 on 2018-08-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0025_auto_20180815_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(help_text='标签集', max_length=200, null=True, verbose_name='标签集'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='desc',
            field=models.CharField(help_text='内容', max_length=800, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(help_text='标签集', max_length=200, null=True, verbose_name='标签集'),
        ),
    ]
