# Generated by Django 2.0.3 on 2018-08-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0028_auto_20180820_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='register_time',
            field=models.DateTimeField(help_text='注册日期', verbose_name='注册日期'),
        ),
    ]
