# Generated by Django 2.0.3 on 2018-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0031_auto_20180821_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.CharField(help_text='标签集', max_length=500, verbose_name='标签集'),
        ),
    ]
