# Generated by Django 2.0.3 on 2018-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0032_auto_20180825_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.CharField(help_text='标签集', max_length=800, verbose_name='标签集'),
        ),
    ]
