# Generated by Django 2.0.3 on 2018-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bili', '0033_auto_20180825_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_count', models.IntegerField(default=0, help_text='投稿总数', verbose_name='投稿总数')),
                ('web_online', models.IntegerField(default=0, help_text='当前在线人数', verbose_name='当前在线人数')),
                ('play_online', models.IntegerField(default=0, help_text='在线观看人数', verbose_name='在线观看人数')),
                ('current_time', models.DateTimeField(help_text='投稿总数', null=True, verbose_name='投稿总数')),
            ],
            options={
                'verbose_name': '在线人数统计',
                'verbose_name_plural': '在线人数统计',
            },
        ),
    ]
